### ISSUE TITLE
No data after the indexedDB database creation

### ISSUE THREAD

**Issue by harry-73** [jamauro/offline#12]
The first the application is launched, the indexedDB database is created but it remains empty. After reloaded the web page, the database is fulfilled.

**Comment by jamauro** [comment]
I wasn't able to repro this. If you can provide a minimal repro, that would be helpful. Can you repro when not using `vite`? This seems very similar to the other issue https://github.com/jamauro/offline/issues/11 you opened so maybe it's the same root cause.

**Comment by jamauro** [comment]
I believe this is the same root cause as #11. Closing as it should be fixed in `v0.3.1`

**Comment by harry-73** [comment]
I confirm. It is fixed.
