### ISSUE TITLE
Error calling queueMethod

### ISSUE THREAD

**Issue by harry-73** [jamauro/offline#13]
I have the following error when calling `queueMethod`:

```
Error mymethod : DOMException: Failed to execute 'add' on 'IDBObjectStore': [object Array] could not be cloned.
    at Proxy.<anonymous> (http://localhost:3000/packages/jam_offline.js?hash=1fcac9ddb030cb3b506317e41cf765379c1f4736:1364:26)
    at Proxy.method (http://localhost:3000/packages/jam_offline.js?hash=1fcac9ddb030cb3b506317e41cf765379c1f4736:1477:35)
    at queueMethod (http://localhost:3000/packages/jam_offline.js?hash=1fcac9ddb030cb3b506317e41cf765379c1f4736:562:13)
```

I am offline and call `queueMethod('mymethod', args)`
with 
```
const args = {
        "name": "Foo",
        "type": "Blabla",
        "description": "...",
        "time": "00:00:03",
        "dateActivity": "2100-08-23T14:16:07+02:00",
        "distance": 0,
        "Notes": [],
        "checked": [],
        "geojson": [
            {
                "type": "Feature",
                "properties": {
                    "time": "",
                    "coordinateProperties": {
                        "times": [],
                        "heart": []
                    }
                },
                "geometry": {
                    "type": "LineString",
                    "coordinates": []
                }
            }
        ]
}
```

**Comment by jamauro** [comment]
Can you provide a full sample of the data please? Based on the error, it sounds like it could be an issue with how indexedDB uses `structuredClone` internally.

**Comment by harry-73** [comment]
It is  already the full sample of the data.

**Comment by jamauro** [comment]
Hmm I wasn't able to repro using that sample. Is it possible that something in the data is `undefined` when you're trying to queue the method?

<img width="1106" alt="Screenshot 2024-08-23 at 9 16 15 AM" src="https://github.com/user-attachments/assets/fc207278-4886-46a5-ac9f-61c748fddafc">

**Comment by harry-73** [comment]
I will try to reproduce it in a simple repo

**Comment by harry-73** [comment]
I am not able to reproduce in the simple repo with vite. 
The object is directly the one taken from Dev Tools. So no `undefined` 

![image](https://github.com/user-attachments/assets/845bb037-9f19-48b3-9310-5302ce7fa7d7)

**Comment by harry-73** [comment]
I found the issue.

The problem is with the `Proxy(Array)` that idb seems not like it. 

So I modifed my code like that 

before:

```
queueMethod('mymethod', args)
```

After:

```
args = JSON.parse( JSON.stringify(args));
queueMethod('mymethod', args)
```

In my first message, I took the output of the devtools for the object. So, It was not my real data.

**Comment by jamauro** [comment]
Ok sounds like this issue can be closed.
