### ISSUE TITLE
Filter on server side on _keep method does not work

### ISSUE THREAD

**Issue by harry-73** [jamauro/offline#16]
Hi,

The current filter returns 0 entries:

` const finalFilter = { $and: [{ $nor: [replacedFilter] }, { [sortKey]: { $gt: syncedAt } }] };`

By modify it like that, it works as excepted:

` const finalFilter = { $and: [{ $nor: [replacedFilter] }, { [sortKey]: { $gt: new Date(syncedAt) } }] };`

**Comment by jamauro** [comment]
Interesting. Seems like a simple enough change but I’m wondering why I haven’t experienced this. 

Can you provide the repro steps? Thanks

**Comment by jamauro** [comment]
I couldn't repro this. I verified that `syncedAt` is being passed correctly as a `Date` object.
