### ISSUE TITLE
Failed to execute 'get' on 'IDBObjectStore': The parameter is not a valid key.

### ISSUE THREAD

**Issue by harry-73** [jamauro/offline#6]
I am using 0.1.2

The collections are present in the IndexedDB but no documents.

The error is at line 62 of `idb.js` file
```
  if (!limit) { // there's no limit, so we put the doc
    return finishPut();
  }

  const existingDoc = await store.get(doc._id); // Error
  const count = await store.count() + (existingDoc ? 0 : 1); // if we're adding a new doc, we anticipate it and increase the count by 1

  if (count <= limit) { // we're under the limit, so put the doc
    return finishPut();
```

In Minimongo, the _id are in Mongo format.

**Comment by jamauro** [comment]
I just published `v0.2.0` which adds support for `Mongo.ObjectID` 🎉. This should fix this issue.

**Comment by jamauro** [comment]
Closing since this should be fixed. If you're seeing issues, feel free to re-open.

**Comment by harry-73** [comment]
I confirmed. It is fixed.
